spring:
  application:
    name: authentication-service

  config:
    import: configserver:http://localhost:${CONFIG_SERVICE_PORT}

  cloud:
    config:
      uri: https://github.com/Timo0ooon/config.git