server:
  port: ${DISCOVERY_SERVICE_PORT}

spring:
  application:
    name:
      discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
