spring:
  application:
    name: moex-notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: moex-data.currencies

#  mail:
#    username: .  # Gmail
#    password: .  # App password
#    host: smtp.gmail.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8081

kafka:
  topic: quotation.moex-data.currencies
